language: php
sudo: false
php:
  - 7.1
  - 7.2
  - night
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script: vendor/bin/phpunit --coverage-clover=coverage.xml
